version: '3'

services:
  postgres:
    image: postgres:14.1-alpine
    container_name: sms_db
    environment:
      POSTGRES_DB: sms_db
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.2.1-alpine
    container_name: sms_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
