version: '3'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    volumes:
      - ./:/app
    environment:
      - NODE_ENV=development
    depends_on:
      - db
  
  db:
    image: postgres:14.1-alpine
    container_name: sms_db
    environment:
      POSTGRES_DB: sms_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
  redis:
    image: redis:7.2.1-alpine
    container_name: sms_redis
    ports:
      - "6379:6379"

volumes:
  postgres_data:
  app_data:
